[package]
authors = ["Ockam Developers"]
edition = "2018"
name = "ockam-vault-software"
version = "0.1.0"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[profile.release]
lto = true

[dependencies]
ockam-common = { version = "0.1", path = "../../common" }
ockam-vault = { version = "0.1", path = "../traits" }
aead = "0.3"
aes-gcm = "0.8"
arrayref = "0.3"
curve25519-dalek = "3.0"
ed25519-dalek = "1.0"
hkdf = "0.9"
p256 = { version = "0.5", features = ["arithmetic", "zeroize"] }
rand = "0.7"
sha2 = "0.9"
x25519-dalek = "1.0"
zeroize = { version = "1.1", features = ["zeroize_derive"] }

[dev-dependencies]
hex = "0.4"