[package]
authors = ["Ockam Developers"]
edition = "2018"
name = "ockam-vault-file"
version = "0.1.0"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[profile.release]
lto = true

[dependencies]
ockam-common = { version = "0.1", path = "../../common" }
ockam-vault = { version = "0.1", path = "../traits" }
ockam-vault-software = { version = "0.1", path = "../software" }
zeroize = { version = "1.1", features = ["zeroize_derive"] }